name: deci2file
sha1: ede355ab998451338ac6366609cdb0a19c023654
options:
    # paths
    basename: deci2file
    target_path: in/DECI2FILE.rom
    base_path: ../..
    
    asm_path: asm/deci2file
    src_path: src/deci2file
    asset_path: assets/deci2file
    build_path: build
    subalign: 4

    extensions_path: tools/splat_ext 
    symbol_addrs_path: config/deci2file/symbol_addrs.txt
    reloc_addrs_path: config/deci2file/reloc_addrs.txt
    undefined_funcs_auto_path: config/deci2file/undefined_funcs_auto.txt
    undefined_syms_auto_path:  config/deci2file/undefined_syms_auto.txt

    migrate_rodata_to_functions: True
    named_regs_for_c_funcs: False
    make_full_disasm_for_code: True

    # compiler 
    compiler: GCC
    platform: psx

    string_encoding: ASCII
    
    section_order: [".text", ".rodata", ".data", ".bss"]

segments:
    - name: main
      type: code
      start: 0x0
      vram: 0x0
      bss_size: 0x10d8
      subsegments:
        # .text
        - [0x0, c, main]
        - [0x3350, asm, ilb_stub]
        - [0x3520, .rodata, main]
        - [0x3940, data, main]

        # .sbss / .bss
        - { type: bss, vram: 0x3ca0, name: deci2file }

    - [0x3ca0]
        
