.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.40.0 */

glabel func_00004EF0
    /* 4EF0 00004EF0 0A00C010 */  beqz       $a2, .L00004F1C
    /* 4EF4 00004EF4 00000224 */   addiu     $v0, $zero, 0x0
    /* 4EF8 00004EF8 21388600 */  addu       $a3, $a0, $a2
  .L00004EFC:
    /* 4EFC 00004EFC 00008390 */  lbu        $v1, 0x0($a0)
    /* 4F00 00004F00 00000000 */  nop
    /* 4F04 00004F04 0000A3A0 */  sb         $v1, 0x0($a1)
    /* 4F08 00004F08 01008424 */  addiu      $a0, $a0, 0x1
    /* 4F0C 00004F0C 0100A524 */  addiu      $a1, $a1, 0x1
    /* 4F10 00004F10 2B088700 */  sltu       $at, $a0, $a3
    /* 4F14 00004F14 F9FF2014 */  bnez       $at, .L00004EFC
    /* 4F18 00004F18 00000000 */   nop
  .L00004F1C:
    /* 4F1C 00004F1C 0800E003 */  jr         $ra
    /* 4F20 00004F20 00000000 */   nop
endlabel func_00004EF0

glabel func_00004F24
    /* 4F24 00004F24 FEFF0224 */  addiu      $v0, $zero, -0x2
    /* 4F28 00004F28 2430C200 */  and        $a2, $a2, $v0
    /* 4F2C 00004F2C 0A00C010 */  beqz       $a2, .L00004F58
    /* 4F30 00004F30 00000224 */   addiu     $v0, $zero, 0x0
    /* 4F34 00004F34 21388600 */  addu       $a3, $a0, $a2
  .L00004F38:
    /* 4F38 00004F38 00008394 */  lhu        $v1, 0x0($a0)
    /* 4F3C 00004F3C 00000000 */  nop
    /* 4F40 00004F40 0000A3A4 */  sh         $v1, 0x0($a1)
    /* 4F44 00004F44 02008424 */  addiu      $a0, $a0, 0x2
    /* 4F48 00004F48 0200A524 */  addiu      $a1, $a1, 0x2
    /* 4F4C 00004F4C 2B088700 */  sltu       $at, $a0, $a3
    /* 4F50 00004F50 F9FF2014 */  bnez       $at, .L00004F38
    /* 4F54 00004F54 00000000 */   nop
  .L00004F58:
    /* 4F58 00004F58 0800E003 */  jr         $ra
    /* 4F5C 00004F5C 00000000 */   nop
endlabel func_00004F24

glabel func_00004F60
    /* 4F60 00004F60 FCFF0224 */  addiu      $v0, $zero, -0x4
    /* 4F64 00004F64 2430C200 */  and        $a2, $a2, $v0
    /* 4F68 00004F68 0A00C010 */  beqz       $a2, .L00004F94
    /* 4F6C 00004F6C 00000224 */   addiu     $v0, $zero, 0x0
    /* 4F70 00004F70 21388600 */  addu       $a3, $a0, $a2
  .L00004F74:
    /* 4F74 00004F74 0000838C */  lw         $v1, 0x0($a0)
    /* 4F78 00004F78 00000000 */  nop
    /* 4F7C 00004F7C 0000A3AC */  sw         $v1, 0x0($a1)
    /* 4F80 00004F80 04008424 */  addiu      $a0, $a0, 0x4
    /* 4F84 00004F84 0400A524 */  addiu      $a1, $a1, 0x4
    /* 4F88 00004F88 2B088700 */  sltu       $at, $a0, $a3
    /* 4F8C 00004F8C F9FF2014 */  bnez       $at, .L00004F74
    /* 4F90 00004F90 00000000 */   nop
  .L00004F94:
    /* 4F94 00004F94 0800E003 */  jr         $ra
    /* 4F98 00004F98 00000000 */   nop
endlabel func_00004F60

/* Handwritten function */
glabel func_00004F9C
    /* 4F9C 00004F9C 00000000 */  nop
    /* 4FA0 00004FA0 00000000 */  nop
    /* 4FA4 00004FA4 00381B40 */  mfc0       $k1, $7 /* handwritten instruction */
    /* 4FA8 00004FA8 00388040 */  mtc0       $zero, $7 /* handwritten instruction */
    /* 4FAC 00004FAC 30041BAC */  sw         $k1, 0x430($zero) /* handwritten instruction */
    /* 4FB0 00004FB0 01001A3C */  lui        $k0, %hi(D_0000FE20) /* handwritten instruction */
    /* 4FB4 00004FB4 20FE5A27 */  addiu      $k0, $k0, %lo(D_0000FE20) /* handwritten instruction */
    /* 4FB8 00004FB8 040042AF */  sw         $v0, 0x4($k0) /* handwritten instruction */
    /* 4FBC 00004FBC 080043AF */  sw         $v1, 0x8($k0) /* handwritten instruction */
    /* 4FC0 00004FC0 000041AF */  sw         $at, 0x0($k0) /* handwritten instruction */
    /* 4FC4 00004FC4 0404028C */  lw         $v0, 0x404($zero)
    /* 4FC8 00004FC8 FF1F1A3C */  lui        $k0, (0x1FFFFFFF >> 16) /* handwritten instruction */
    /* 4FCC 00004FCC FFFF5A37 */  ori        $k0, $k0, (0x1FFFFFFF & 0xFFFF) /* handwritten instruction */
    /* 4FD0 00004FD0 24105A00 */  and        $v0, $v0, $k0
    /* 4FD4 00004FD4 00000000 */  nop
    /* 4FD8 00004FD8 0000033C */  lui        $v1, %hi(func_00004EF0)
    /* 4FDC 00004FDC F04E6324 */  addiu      $v1, $v1, %lo(func_00004EF0)
    /* 4FE0 00004FE0 24187A00 */  and        $v1, $v1, $k0
    /* 4FE4 00004FE4 2B084300 */  sltu       $at, $v0, $v1
    /* 4FE8 00004FE8 0B002014 */  bnez       $at, .L00005018
    /* 4FEC 00004FEC 00000000 */   nop
    /* 4FF0 00004FF0 0000033C */  lui        $v1, %hi(func_00004F9C)
    /* 4FF4 00004FF4 9C4F6324 */  addiu      $v1, $v1, %lo(func_00004F9C)
    /* 4FF8 00004FF8 24187A00 */  and        $v1, $v1, $k0
    /* 4FFC 00004FFC 2B084300 */  sltu       $at, $v0, $v1
    /* 5000 00005000 05002010 */  beqz       $at, .L00005018
    /* 5004 00005004 00000000 */   nop
    /* 5008 00005008 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 500C 0000500C 0800E003 */  jr         $ra
    /* 5010 00005010 10000042 */   rfe /* handwritten instruction */
    /* 5014 00005014 00000000 */  nop
  .L00005018:
    /* 5018 00005018 01001A3C */  lui        $k0, %hi(D_0000FE20) /* handwritten instruction */
    /* 501C 0000501C 20FE5A27 */  addiu      $k0, $k0, %lo(D_0000FE20) /* handwritten instruction */
    /* 5020 00005020 0000418F */  lw         $at, 0x0($k0) /* handwritten instruction */
    /* 5024 00005024 0400428F */  lw         $v0, 0x4($k0) /* handwritten instruction */
    /* 5028 00005028 0800438F */  lw         $v1, 0x8($k0) /* handwritten instruction */
    /* 502C 0000502C 00001A3C */  lui        $k0, %hi(func_00004F9C) /* handwritten instruction */
    /* 5030 00005030 9C4F5A8F */  lw         $k0, %lo(func_00004F9C)($k0) /* handwritten instruction */
    /* 5034 00005034 30041B8C */  lw         $k1, 0x430($zero) /* handwritten instruction */
    /* 5038 00005038 08004003 */  jr         $k0
    /* 503C 0000503C 00389B40 */   mtc0      $k1, $7 /* handwritten instruction */
    /* 5040 00005040 00000000 */  nop
  jtbl_00005044:
    /* 5044 00005044 00000000 */  nop
    /* 5048 00005048 00000000 */  nop
    /* 504C 0000504C 01001A3C */  lui        $k0, %hi(D_0000FE20) /* handwritten instruction */
    /* 5050 00005050 20FE5A27 */  addiu      $k0, $k0, %lo(D_0000FE20) /* handwritten instruction */
    /* 5054 00005054 000041AF */  sw         $at, 0x0($k0) /* handwritten instruction */
    /* 5058 00005058 040042AF */  sw         $v0, 0x4($k0) /* handwritten instruction */
    /* 505C 0000505C 080043AF */  sw         $v1, 0x8($k0) /* handwritten instruction */
    /* 5060 00005060 0C0050AF */  sw         $s0, 0xC($k0) /* handwritten instruction */
    /* 5064 00005064 100051AF */  sw         $s1, 0x10($k0) /* handwritten instruction */
    /* 5068 00005068 14005FAF */  sw         $ra, 0x14($k0) /* handwritten instruction */
    /* 506C 0000506C 0000103C */  lui        $s0, %hi(unk66F0)
    /* 5070 00005070 F0661026 */  addiu      $s0, $s0, %lo(unk66F0)
    /* 5074 00005074 08001126 */  addiu      $s1, $s0, 0x8
  .L00005078:
    /* 5078 00005078 2B081102 */  sltu       $at, $s0, $s1
    /* 507C 0000507C 0A000110 */  beq        $zero, $at, .L000050A8
    /* 5080 00005080 0000018E */   lw        $at, 0x0($s0)
    /* 5084 00005084 04001026 */  addiu      $s0, $s0, 0x4
    /* 5088 00005088 FBFF2010 */  beqz       $at, .L00005078
    /* 508C 0000508C 00000000 */   nop
    /* 5090 00005090 09F82000 */  jalr       $at
    /* 5094 00005094 00000000 */   nop
    /* 5098 00005098 F7FF0210 */  beq        $zero, $v0, .L00005078
    /* 509C 0000509C 00000000 */   nop
    /* 50A0 000050A0 0E000010 */  b          .L000050DC
    /* 50A4 000050A4 00000000 */   nop
  .L000050A8:
    /* 50A8 000050A8 01001A3C */  lui        $k0, %hi(D_0000FE20) /* handwritten instruction */
    /* 50AC 000050AC 20FE5A27 */  addiu      $k0, $k0, %lo(D_0000FE20) /* handwritten instruction */
    /* 50B0 000050B0 0000418F */  lw         $at, 0x0($k0) /* handwritten instruction */
    /* 50B4 000050B4 0400428F */  lw         $v0, 0x4($k0) /* handwritten instruction */
    /* 50B8 000050B8 0800438F */  lw         $v1, 0x8($k0) /* handwritten instruction */
    /* 50BC 000050BC 0C00508F */  lw         $s0, 0xC($k0) /* handwritten instruction */
    /* 50C0 000050C0 1000518F */  lw         $s1, 0x10($k0) /* handwritten instruction */
    /* 50C4 000050C4 14005F8F */  lw         $ra, 0x14($k0) /* handwritten instruction */
    /* 50C8 000050C8 00001A3C */  lui        $k0, %hi(jtbl_00005044) /* handwritten instruction */
    /* 50CC 000050CC 44505A8F */  lw         $k0, %lo(jtbl_00005044)($k0) /* handwritten instruction */
    /* 50D0 000050D0 00000000 */  nop
    /* 50D4 000050D4 08004003 */  jr         $k0
    /* 50D8 000050D8 00000000 */   nop
  .L000050DC:
    /* 50DC 000050DC 01001A3C */  lui        $k0, %hi(D_0000FE20) /* handwritten instruction */
    /* 50E0 000050E0 20FE5A27 */  addiu      $k0, $k0, %lo(D_0000FE20) /* handwritten instruction */
    /* 50E4 000050E4 0000418F */  lw         $at, 0x0($k0) /* handwritten instruction */
    /* 50E8 000050E8 0400428F */  lw         $v0, 0x4($k0) /* handwritten instruction */
    /* 50EC 000050EC 0800438F */  lw         $v1, 0x8($k0) /* handwritten instruction */
    /* 50F0 000050F0 0C00508F */  lw         $s0, 0xC($k0) /* handwritten instruction */
    /* 50F4 000050F4 1000518F */  lw         $s1, 0x10($k0) /* handwritten instruction */
    /* 50F8 000050F8 14005F8F */  lw         $ra, 0x14($k0) /* handwritten instruction */
    /* 50FC 000050FC 7A140008 */  j          .L000051E8
    /* 5100 00005100 00000000 */   nop
  jtbl_00005104:
    /* 5104 00005104 00000000 */  nop
    /* 5108 00005108 00000000 */  nop
    /* 510C 0000510C 01001B24 */  addiu      $k1, $zero, 0x1 /* handwritten instruction */
    /* 5110 00005110 35006213 */  beq        $k1, $v0, .L000051E8 /* handwritten instruction */
    /* 5114 00005114 00000000 */   nop
    /* 5118 00005118 02001B24 */  addiu      $k1, $zero, 0x2 /* handwritten instruction */
    /* 511C 0000511C 06006213 */  beq        $k1, $v0, .L00005138 /* handwritten instruction */
    /* 5120 00005120 00000000 */   nop
    /* 5124 00005124 00001B3C */  lui        $k1, %hi(jtbl_00005104) /* handwritten instruction */
    /* 5128 00005128 04517B8F */  lw         $k1, %lo(jtbl_00005104)($k1) /* handwritten instruction */
    /* 512C 0000512C 00000000 */  nop
    /* 5130 00005130 08006003 */  jr         $k1
    /* 5134 00005134 00000000 */   nop
  .L00005138:
    /* 5138 00005138 0C04028C */  lw         $v0, 0x40C($zero)
    /* 513C 0000513C 00010324 */  addiu      $v1, $zero, 0x100
    /* 5140 00005140 25104300 */  or         $v0, $v0, $v1
    /* 5144 00005144 00688240 */  mtc0       $v0, $13 /* handwritten instruction */
    /* 5148 00005148 0804028C */  lw         $v0, 0x408($zero)
    /* 514C 0000514C 00010324 */  addiu      $v1, $zero, 0x100
    /* 5150 00005150 25104300 */  or         $v0, $v0, $v1
    /* 5154 00005154 00608240 */  mtc0       $v0, $12 /* handwritten instruction */
    /* 5158 00005158 0404028C */  lw         $v0, 0x404($zero)
    /* 515C 0000515C 00000000 */  nop
    /* 5160 00005160 04004224 */  addiu      $v0, $v0, 0x4
    /* 5164 00005164 08004000 */  jr         $v0
    /* 5168 00005168 10000042 */   rfe /* handwritten instruction */
  alabel D_0000516C
    /* 516C 0000516C 00000000 */  nop
    /* 5170 00005170 00000000 */  nop
    /* 5174 00005174 01001B3C */  lui        $k1, %hi(jtbl_0000FE40) /* handwritten instruction */
    /* 5178 00005178 40FE7B27 */  addiu      $k1, $k1, %lo(jtbl_0000FE40) /* handwritten instruction */
    /* 517C 0000517C 20041A8C */  lw         $k0, 0x420($zero) /* handwritten instruction */
    /* 5180 00005180 040061AF */  sw         $at, 0x4($k1) /* handwritten instruction */
    /* 5184 00005184 68007AAF */  sw         $k0, 0x68($k1) /* handwritten instruction */
    /* 5188 00005188 24041A8C */  lw         $k0, 0x424($zero) /* handwritten instruction */
    /* 518C 0000518C 2C04018C */  lw         $at, 0x42C($zero)
    /* 5190 00005190 80007AAF */  sw         $k0, 0x80($k1) /* handwritten instruction */
    /* 5194 00005194 8C0061AF */  sw         $at, 0x8C($k1) /* handwritten instruction */
    /* 5198 00005198 28041A8C */  lw         $k0, 0x428($zero) /* handwritten instruction */
    /* 519C 0000519C 3004018C */  lw         $at, 0x430($zero)
    /* 51A0 000051A0 90007AAF */  sw         $k0, 0x90($k1) /* handwritten instruction */
    /* 51A4 000051A4 9C0061AF */  sw         $at, 0x9C($k1) /* handwritten instruction */
    /* 51A8 000051A8 01001B24 */  addiu      $k1, $zero, 0x1 /* handwritten instruction */
    /* 51AC 000051AC 34041BAC */  sw         $k1, 0x434($zero) /* handwritten instruction */
    /* 51B0 000051B0 8C140008 */  j          .L00005230
    /* 51B4 000051B4 00000000 */   nop
  alabel D_000051B8
    /* 51B8 000051B8 00000000 */  nop
    /* 51BC 000051BC 00000000 */  nop
    /* 51C0 000051C0 7A140008 */  j          .L000051E8
    /* 51C4 000051C4 00000000 */   nop
  alabel D_000051C8
    /* 51C8 000051C8 00000000 */  nop
    /* 51CC 000051CC 00000000 */  nop
    /* 51D0 000051D0 00381A40 */  mfc0       $k0, $7 /* handwritten instruction */
    /* 51D4 000051D4 00388040 */  mtc0       $zero, $7 /* handwritten instruction */
    /* 51D8 000051D8 02001B24 */  addiu      $k1, $zero, 0x2 /* handwritten instruction */
    /* 51DC 000051DC 34041BAC */  sw         $k1, 0x434($zero) /* handwritten instruction */
    /* 51E0 000051E0 04000010 */  b          .L000051F4
    /* 51E4 000051E4 00000000 */   nop
  .L000051E8:
    /* 51E8 000051E8 00381A40 */  mfc0       $k0, $7 /* handwritten instruction */
    /* 51EC 000051EC 00388040 */  mtc0       $zero, $7 /* handwritten instruction */
    /* 51F0 000051F0 340400AC */  sw         $zero, 0x434($zero)
  .L000051F4:
    /* 51F4 000051F4 01001B3C */  lui        $k1, %hi(jtbl_0000FE40) /* handwritten instruction */
    /* 51F8 000051F8 40FE7B27 */  addiu      $k1, $k1, %lo(jtbl_0000FE40) /* handwritten instruction */
    /* 51FC 000051FC 1004018C */  lw         $at, 0x410($zero)
    /* 5200 00005200 9C007AAF */  sw         $k0, 0x9C($k1) /* handwritten instruction */
    /* 5204 00005204 680061AF */  sw         $at, 0x68($k1) /* handwritten instruction */
    /* 5208 00005208 04041A8C */  lw         $k0, 0x404($zero) /* handwritten instruction */
    /* 520C 0000520C 0804018C */  lw         $at, 0x408($zero)
    /* 5210 00005210 80007AAF */  sw         $k0, 0x80($k1) /* handwritten instruction */
    /* 5214 00005214 8C0061AF */  sw         $at, 0x8C($k1) /* handwritten instruction */
    /* 5218 00005218 0C041A8C */  lw         $k0, 0x40C($zero) /* handwritten instruction */
    /* 521C 0000521C 0004018C */  lw         $at, 0x400($zero)
    /* 5220 00005220 90007AAF */  sw         $k0, 0x90($k1) /* handwritten instruction */
    /* 5224 00005224 040061AF */  sw         $at, 0x4($k1) /* handwritten instruction */
    /* 5228 00005228 8C140008 */  j          .L00005230
    /* 522C 0000522C 00000000 */   nop
  .L00005230:
    /* 5230 00005230 01001B3C */  lui        $k1, %hi(jtbl_0000FE40) /* handwritten instruction */
    /* 5234 00005234 40FE7B27 */  addiu      $k1, $k1, %lo(jtbl_0000FE40) /* handwritten instruction */
    /* 5238 00005238 080062AF */  sw         $v0, 0x8($k1) /* handwritten instruction */
    /* 523C 0000523C 0C0063AF */  sw         $v1, 0xC($k1) /* handwritten instruction */
    /* 5240 00005240 100064AF */  sw         $a0, 0x10($k1) /* handwritten instruction */
    /* 5244 00005244 140065AF */  sw         $a1, 0x14($k1) /* handwritten instruction */
    /* 5248 00005248 180066AF */  sw         $a2, 0x18($k1) /* handwritten instruction */
    /* 524C 0000524C 1C0067AF */  sw         $a3, 0x1C($k1) /* handwritten instruction */
    /* 5250 00005250 200068AF */  sw         $t0, 0x20($k1) /* handwritten instruction */
    /* 5254 00005254 240069AF */  sw         $t1, 0x24($k1) /* handwritten instruction */
    /* 5258 00005258 28006AAF */  sw         $t2, 0x28($k1) /* handwritten instruction */
    /* 525C 0000525C 2C006BAF */  sw         $t3, 0x2C($k1) /* handwritten instruction */
    /* 5260 00005260 30006CAF */  sw         $t4, 0x30($k1) /* handwritten instruction */
    /* 5264 00005264 34006DAF */  sw         $t5, 0x34($k1) /* handwritten instruction */
    /* 5268 00005268 38006EAF */  sw         $t6, 0x38($k1) /* handwritten instruction */
    /* 526C 0000526C 3C006FAF */  sw         $t7, 0x3C($k1) /* handwritten instruction */
    /* 5270 00005270 400070AF */  sw         $s0, 0x40($k1) /* handwritten instruction */
    /* 5274 00005274 440071AF */  sw         $s1, 0x44($k1) /* handwritten instruction */
    /* 5278 00005278 480072AF */  sw         $s2, 0x48($k1) /* handwritten instruction */
    /* 527C 0000527C 4C0073AF */  sw         $s3, 0x4C($k1) /* handwritten instruction */
    /* 5280 00005280 500074AF */  sw         $s4, 0x50($k1) /* handwritten instruction */
    /* 5284 00005284 540075AF */  sw         $s5, 0x54($k1) /* handwritten instruction */
    /* 5288 00005288 580076AF */  sw         $s6, 0x58($k1) /* handwritten instruction */
    /* 528C 0000528C 5C0077AF */  sw         $s7, 0x5C($k1) /* handwritten instruction */
    /* 5290 00005290 600078AF */  sw         $t8, 0x60($k1) /* handwritten instruction */
    /* 5294 00005294 640079AF */  sw         $t9, 0x64($k1) /* handwritten instruction */
    /* 5298 00005298 70007CAF */  sw         $gp, 0x70($k1) /* handwritten instruction */
    /* 529C 0000529C 74007DAF */  sw         $sp, 0x74($k1) /* handwritten instruction */
    /* 52A0 000052A0 78007EAF */  sw         $fp, 0x78($k1) /* handwritten instruction */
    /* 52A4 000052A4 7C007FAF */  sw         $ra, 0x7C($k1) /* handwritten instruction */
    /* 52A8 000052A8 10400000 */  mfhi       $t0
    /* 52AC 000052AC 12480000 */  mflo       $t1
    /* 52B0 000052B0 840068AF */  sw         $t0, 0x84($k1) /* handwritten instruction */
    /* 52B4 000052B4 880069AF */  sw         $t1, 0x88($k1) /* handwritten instruction */
    /* 52B8 000052B8 00300840 */  mfc0       $t0, $6 /* handwritten instruction */
    /* 52BC 000052BC 00400940 */  mfc0       $t1, $8 /* handwritten instruction */
    /* 52C0 000052C0 940068AF */  sw         $t0, 0x94($k1) /* handwritten instruction */
    /* 52C4 000052C4 980069AF */  sw         $t1, 0x98($k1) /* handwritten instruction */
    /* 52C8 000052C8 00180840 */  mfc0       $t0, $3 /* handwritten instruction */
    /* 52CC 000052CC 00580940 */  mfc0       $t1, $11 /* handwritten instruction */
    /* 52D0 000052D0 A00068AF */  sw         $t0, 0xA0($k1) /* handwritten instruction */
    /* 52D4 000052D4 A40069AF */  sw         $t1, 0xA4($k1) /* handwritten instruction */
    /* 52D8 000052D8 00280840 */  mfc0       $t0, $5 /* handwritten instruction */
    /* 52DC 000052DC 00480940 */  mfc0       $t1, $9 /* handwritten instruction */
    /* 52E0 000052E0 A80068AF */  sw         $t0, 0xA8($k1) /* handwritten instruction */
    /* 52E4 000052E4 AC0069AF */  sw         $t1, 0xAC($k1) /* handwritten instruction */
    /* 52E8 000052E8 00001D3C */  lui        $sp, %hi(D_000066E0)
    /* 52EC 000052EC E066BD8F */  lw         $sp, %lo(D_000066E0)($sp)
    /* 52F0 000052F0 00000000 */  nop
    /* 52F4 000052F4 21F0A003 */  addu       $fp, $sp, $zero
    /* 52F8 000052F8 01001C3C */  lui        $gp, %hi(_gp)
    /* 52FC 000052FC 540E000C */  jal        func_00003950
    /* 5300 00005300 E0E69C27 */   addiu     $gp, $gp, %lo(_gp)
    /* 5304 00005304 01001B3C */  lui        $k1, %hi(jtbl_0000FE40) /* handwritten instruction */
    /* 5308 00005308 40FE7B27 */  addiu      $k1, $k1, %lo(jtbl_0000FE40) /* handwritten instruction */
    /* 530C 0000530C 9C00688F */  lw         $t0, 0x9C($k1) /* handwritten instruction */
    /* 5310 00005310 C0FF0924 */  addiu      $t1, $zero, -0x40
    /* 5314 00005314 24400901 */  and        $t0, $t0, $t1
    /* 5318 00005318 9C0068AF */  sw         $t0, 0x9C($k1) /* handwritten instruction */
    /* 531C 0000531C 8400688F */  lw         $t0, 0x84($k1) /* handwritten instruction */
    /* 5320 00005320 8800698F */  lw         $t1, 0x88($k1) /* handwritten instruction */
    /* 5324 00005324 8C006A8F */  lw         $t2, 0x8C($k1) /* handwritten instruction */
    /* 5328 00005328 11000001 */  mthi       $t0
    /* 532C 0000532C 13002001 */  mtlo       $t1
    /* 5330 00005330 FCFF0824 */  addiu      $t0, $zero, -0x4
    /* 5334 00005334 24504801 */  and        $t2, $t2, $t0
    /* 5338 00005338 00608A40 */  mtc0       $t2, $12 /* handwritten instruction */
    /* 533C 0000533C 9000688F */  lw         $t0, 0x90($k1) /* handwritten instruction */
    /* 5340 00005340 A000698F */  lw         $t1, 0xA0($k1) /* handwritten instruction */
    /* 5344 00005344 A4006A8F */  lw         $t2, 0xA4($k1) /* handwritten instruction */
    /* 5348 00005348 00688840 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 534C 0000534C 00188940 */  mtc0       $t1, $3 /* handwritten instruction */
    /* 5350 00005350 00588A40 */  mtc0       $t2, $11 /* handwritten instruction */
    /* 5354 00005354 A800688F */  lw         $t0, 0xA8($k1) /* handwritten instruction */
    /* 5358 00005358 AC00698F */  lw         $t1, 0xAC($k1) /* handwritten instruction */
    /* 535C 0000535C 00288840 */  mtc0       $t0, $5 /* handwritten instruction */
    /* 5360 00005360 00488940 */  mtc0       $t1, $9 /* handwritten instruction */
    /* 5364 00005364 0400618F */  lw         $at, 0x4($k1) /* handwritten instruction */
    /* 5368 00005368 0800628F */  lw         $v0, 0x8($k1) /* handwritten instruction */
    /* 536C 0000536C 0C00638F */  lw         $v1, 0xC($k1) /* handwritten instruction */
    /* 5370 00005370 1000648F */  lw         $a0, 0x10($k1) /* handwritten instruction */
    /* 5374 00005374 1400658F */  lw         $a1, 0x14($k1) /* handwritten instruction */
    /* 5378 00005378 1800668F */  lw         $a2, 0x18($k1) /* handwritten instruction */
    /* 537C 0000537C 1C00678F */  lw         $a3, 0x1C($k1) /* handwritten instruction */
    /* 5380 00005380 2000688F */  lw         $t0, 0x20($k1) /* handwritten instruction */
    /* 5384 00005384 2400698F */  lw         $t1, 0x24($k1) /* handwritten instruction */
    /* 5388 00005388 28006A8F */  lw         $t2, 0x28($k1) /* handwritten instruction */
    /* 538C 0000538C 2C006B8F */  lw         $t3, 0x2C($k1) /* handwritten instruction */
    /* 5390 00005390 30006C8F */  lw         $t4, 0x30($k1) /* handwritten instruction */
    /* 5394 00005394 34006D8F */  lw         $t5, 0x34($k1) /* handwritten instruction */
    /* 5398 00005398 38006E8F */  lw         $t6, 0x38($k1) /* handwritten instruction */
    /* 539C 0000539C 3C006F8F */  lw         $t7, 0x3C($k1) /* handwritten instruction */
    /* 53A0 000053A0 4000708F */  lw         $s0, 0x40($k1) /* handwritten instruction */
    /* 53A4 000053A4 4400718F */  lw         $s1, 0x44($k1) /* handwritten instruction */
    /* 53A8 000053A8 4800728F */  lw         $s2, 0x48($k1) /* handwritten instruction */
    /* 53AC 000053AC 4C00738F */  lw         $s3, 0x4C($k1) /* handwritten instruction */
    /* 53B0 000053B0 5000748F */  lw         $s4, 0x50($k1) /* handwritten instruction */
    /* 53B4 000053B4 5400758F */  lw         $s5, 0x54($k1) /* handwritten instruction */
    /* 53B8 000053B8 5800768F */  lw         $s6, 0x58($k1) /* handwritten instruction */
    /* 53BC 000053BC 5C00778F */  lw         $s7, 0x5C($k1) /* handwritten instruction */
    /* 53C0 000053C0 6000788F */  lw         $t8, 0x60($k1) /* handwritten instruction */
    /* 53C4 000053C4 6400798F */  lw         $t9, 0x64($k1) /* handwritten instruction */
    /* 53C8 000053C8 70007C8F */  lw         $gp, 0x70($k1) /* handwritten instruction */
    /* 53CC 000053CC 74007D8F */  lw         $sp, 0x74($k1) /* handwritten instruction */
    /* 53D0 000053D0 78007E8F */  lw         $fp, 0x78($k1) /* handwritten instruction */
    /* 53D4 000053D4 7C007F8F */  lw         $ra, 0x7C($k1) /* handwritten instruction */
    /* 53D8 000053D8 9C007A8F */  lw         $k0, 0x9C($k1) /* handwritten instruction */
    /* 53DC 000053DC 80007B8F */  lw         $k1, 0x80($k1) /* handwritten instruction */
    /* 53E0 000053E0 68007A8F */  lw         $k0, 0x68($k1) /* handwritten instruction */
    /* 53E4 000053E4 00389A40 */  mtc0       $k0, $7 /* handwritten instruction */
    /* 53E8 000053E8 08006003 */  jr         $k1
    /* 53EC 000053EC 10000042 */   rfe /* handwritten instruction */
    /* 53F0 000053F0 00380240 */  mfc0       $v0, $7 /* handwritten instruction */
    /* 53F4 000053F4 03000010 */  b          .L00005404
    /* 53F8 000053F8 00388040 */   mtc0      $zero, $7 /* handwritten instruction */
    /* 53FC 000053FC 01000010 */  b          .L00005404
    /* 5400 00005400 00300240 */   mfc0      $v0, $6 /* handwritten instruction */
  .L00005404:
    /* 5404 00005404 0800E003 */  jr         $ra
    /* 5408 00005408 00000000 */   nop
endlabel func_00004F9C

/* Handwritten function */
glabel func_0000540C
    /* 540C 0000540C FDFF0010 */  b          .L00005404
    /* 5410 00005410 00780240 */   mfc0      $v0, $15 /* handwritten instruction */
endlabel func_0000540C

/* Handwritten function */
glabel func_00005414
    /* 5414 00005414 00600840 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 5418 00005418 00000000 */  nop
    /* 541C 0000541C 0040093C */  lui        $t1, (0x40000000 >> 16)
    /* 5420 00005420 25400901 */  or         $t0, $t0, $t1
    /* 5424 00005424 00608840 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 5428 00005428 00000000 */  nop
    /* 542C 0000542C C0200400 */  sll        $a0, $a0, 3
    /* 5430 00005430 0000083C */  lui        $t0, %hi(D_00005444)
    /* 5434 00005434 44540825 */  addiu      $t0, $t0, %lo(D_00005444)
    /* 5438 00005438 20400401 */  add        $t0, $t0, $a0 /* handwritten instruction */
    /* 543C 0000543C 08000001 */  jr         $t0
    /* 5440 00005440 00000000 */   nop
  alabel D_00005444
    /* 5444 00005444 EFFF0010 */  b          .L00005404
    /* 5448 00005448 00000248 */   mfc2      $v0, $0 /* handwritten instruction */
    /* 544C 0000544C EDFF0010 */  b          .L00005404
    /* 5450 00005450 00080248 */   mfc2      $v0, $1 /* handwritten instruction */
    /* 5454 00005454 EBFF0010 */  b          .L00005404
    /* 5458 00005458 00100248 */   mfc2      $v0, $2 /* handwritten instruction */
    /* 545C 0000545C E9FF0010 */  b          .L00005404
    /* 5460 00005460 00180248 */   mfc2      $v0, $3 /* handwritten instruction */
    /* 5464 00005464 E7FF0010 */  b          .L00005404
    /* 5468 00005468 00200248 */   mfc2      $v0, $4 /* handwritten instruction */
    /* 546C 0000546C E5FF0010 */  b          .L00005404
    /* 5470 00005470 00280248 */   mfc2      $v0, $5 /* handwritten instruction */
    /* 5474 00005474 E3FF0010 */  b          .L00005404
    /* 5478 00005478 00300248 */   mfc2      $v0, $6 /* handwritten instruction */
    /* 547C 0000547C E1FF0010 */  b          .L00005404
    /* 5480 00005480 00380248 */   mfc2      $v0, $7 /* handwritten instruction */
    /* 5484 00005484 DFFF0010 */  b          .L00005404
    /* 5488 00005488 00400248 */   mfc2      $v0, $8 /* handwritten instruction */
    /* 548C 0000548C DDFF0010 */  b          .L00005404
    /* 5490 00005490 00480248 */   mfc2      $v0, $9 /* handwritten instruction */
    /* 5494 00005494 DBFF0010 */  b          .L00005404
    /* 5498 00005498 00500248 */   mfc2      $v0, $10 /* handwritten instruction */
    /* 549C 0000549C D9FF0010 */  b          .L00005404
    /* 54A0 000054A0 00580248 */   mfc2      $v0, $11 /* handwritten instruction */
    /* 54A4 000054A4 D7FF0010 */  b          .L00005404
    /* 54A8 000054A8 00600248 */   mfc2      $v0, $12 /* handwritten instruction */
    /* 54AC 000054AC D5FF0010 */  b          .L00005404
    /* 54B0 000054B0 00680248 */   mfc2      $v0, $13 /* handwritten instruction */
    /* 54B4 000054B4 D3FF0010 */  b          .L00005404
    /* 54B8 000054B8 00700248 */   mfc2      $v0, $14 /* handwritten instruction */
    /* 54BC 000054BC 0800E003 */  jr         $ra
    /* 54C0 000054C0 FFFF0220 */   addi      $v0, $zero, -0x1 /* handwritten instruction */
endlabel func_00005414

/* Handwritten function */
glabel func_000054C4
    /* 54C4 000054C4 CFFF0010 */  b          .L00005404
    /* 54C8 000054C8 00800248 */   mfc2      $v0, $16 /* handwritten instruction */
    /* 54CC 000054CC CDFF0010 */  b          .L00005404
    /* 54D0 000054D0 00880248 */   mfc2      $v0, $17 /* handwritten instruction */
    /* 54D4 000054D4 CBFF0010 */  b          .L00005404
    /* 54D8 000054D8 00900248 */   mfc2      $v0, $18 /* handwritten instruction */
    /* 54DC 000054DC C9FF0010 */  b          .L00005404
    /* 54E0 000054E0 00980248 */   mfc2      $v0, $19 /* handwritten instruction */
    /* 54E4 000054E4 C7FF0010 */  b          .L00005404
    /* 54E8 000054E8 00A00248 */   mfc2      $v0, $20 /* handwritten instruction */
    /* 54EC 000054EC C5FF0010 */  b          .L00005404
    /* 54F0 000054F0 00A80248 */   mfc2      $v0, $21 /* handwritten instruction */
    /* 54F4 000054F4 C3FF0010 */  b          .L00005404
    /* 54F8 000054F8 00B00248 */   mfc2      $v0, $22 /* handwritten instruction */
    /* 54FC 000054FC 0800E003 */  jr         $ra
    /* 5500 00005500 FFFF0220 */   addi      $v0, $zero, -0x1 /* handwritten instruction */
endlabel func_000054C4

/* Handwritten function */
glabel func_00005504
    /* 5504 00005504 BFFF0010 */  b          .L00005404
    /* 5508 00005508 00C00248 */   mfc2      $v0, $24 /* handwritten instruction */
    /* 550C 0000550C BDFF0010 */  b          .L00005404
    /* 5510 00005510 00C80248 */   mfc2      $v0, $25 /* handwritten instruction */
    /* 5514 00005514 BBFF0010 */  b          .L00005404
    /* 5518 00005518 00D00248 */   mfc2      $v0, $26 /* handwritten instruction */
    /* 551C 0000551C B9FF0010 */  b          .L00005404
    /* 5520 00005520 00D80248 */   mfc2      $v0, $27 /* handwritten instruction */
    /* 5524 00005524 0800E003 */  jr         $ra
    /* 5528 00005528 FFFF0220 */   addi      $v0, $zero, -0x1 /* handwritten instruction */
endlabel func_00005504

/* Handwritten function */
glabel func_0000552C
    /* 552C 0000552C B5FF0010 */  b          .L00005404
    /* 5530 00005530 00E80248 */   mfc2      $v0, $29 /* handwritten instruction */
    /* 5534 00005534 0800E003 */  jr         $ra
    /* 5538 00005538 FFFF0220 */   addi      $v0, $zero, -0x1 /* handwritten instruction */
endlabel func_0000552C

/* Handwritten function */
glabel func_0000553C
    /* 553C 0000553C B1FF0010 */  b          .L00005404
    /* 5540 00005540 00F80248 */   mfc2      $v0, $31 /* handwritten instruction */
endlabel func_0000553C

/* Handwritten function */
glabel func_00005544
    /* 5544 00005544 00600840 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 5548 00005548 00000000 */  nop
    /* 554C 0000554C 0040093C */  lui        $t1, (0x40000000 >> 16)
    /* 5550 00005550 25400901 */  or         $t0, $t0, $t1
    /* 5554 00005554 00608840 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 5558 00005558 00000000 */  nop
    /* 555C 0000555C C0280500 */  sll        $a1, $a1, 3
    /* 5560 00005560 0000083C */  lui        $t0, %hi(D_00005574)
    /* 5564 00005564 74550825 */  addiu      $t0, $t0, %lo(D_00005574)
    /* 5568 00005568 20400501 */  add        $t0, $t0, $a1 /* handwritten instruction */
    /* 556C 0000556C 08000001 */  jr         $t0
    /* 5570 00005570 00000000 */   nop
  alabel D_00005574
    /* 5574 00005574 A3FF0010 */  b          .L00005404
    /* 5578 00005578 00008448 */   mtc2      $a0, $0 /* handwritten instruction */
    /* 557C 0000557C A1FF0010 */  b          .L00005404
    /* 5580 00005580 00088448 */   mtc2      $a0, $1 /* handwritten instruction */
    /* 5584 00005584 9FFF0010 */  b          .L00005404
    /* 5588 00005588 00108448 */   mtc2      $a0, $2 /* handwritten instruction */
    /* 558C 0000558C 9DFF0010 */  b          .L00005404
    /* 5590 00005590 00188448 */   mtc2      $a0, $3 /* handwritten instruction */
    /* 5594 00005594 9BFF0010 */  b          .L00005404
    /* 5598 00005598 00208448 */   mtc2      $a0, $4 /* handwritten instruction */
    /* 559C 0000559C 99FF0010 */  b          .L00005404
    /* 55A0 000055A0 00288448 */   mtc2      $a0, $5 /* handwritten instruction */
    /* 55A4 000055A4 97FF0010 */  b          .L00005404
    /* 55A8 000055A8 00308448 */   mtc2      $a0, $6 /* handwritten instruction */
    /* 55AC 000055AC 0800E003 */  jr         $ra
    /* 55B0 000055B0 00000000 */   nop
endlabel func_00005544

/* Handwritten function */
glabel func_000055B4
    /* 55B4 000055B4 93FF0010 */  b          .L00005404
    /* 55B8 000055B8 00408448 */   mtc2      $a0, $8 /* handwritten instruction */
    /* 55BC 000055BC 91FF0010 */  b          .L00005404
    /* 55C0 000055C0 00488448 */   mtc2      $a0, $9 /* handwritten instruction */
    /* 55C4 000055C4 8FFF0010 */  b          .L00005404
    /* 55C8 000055C8 00508448 */   mtc2      $a0, $10 /* handwritten instruction */
    /* 55CC 000055CC 8DFF0010 */  b          .L00005404
    /* 55D0 000055D0 00588448 */   mtc2      $a0, $11 /* handwritten instruction */
    /* 55D4 000055D4 8BFF0010 */  b          .L00005404
    /* 55D8 000055D8 00608448 */   mtc2      $a0, $12 /* handwritten instruction */
    /* 55DC 000055DC 89FF0010 */  b          .L00005404
    /* 55E0 000055E0 00688448 */   mtc2      $a0, $13 /* handwritten instruction */
    /* 55E4 000055E4 87FF0010 */  b          .L00005404
    /* 55E8 000055E8 00708448 */   mtc2      $a0, $14 /* handwritten instruction */
    /* 55EC 000055EC 85FF0010 */  b          .L00005404
    /* 55F0 000055F0 00788448 */   mtc2      $a0, $15 /* handwritten instruction */
    /* 55F4 000055F4 83FF0010 */  b          .L00005404
    /* 55F8 000055F8 00808448 */   mtc2      $a0, $16 /* handwritten instruction */
    /* 55FC 000055FC 81FF0010 */  b          .L00005404
    /* 5600 00005600 00888448 */   mtc2      $a0, $17 /* handwritten instruction */
    /* 5604 00005604 7FFF0010 */  b          .L00005404
    /* 5608 00005608 00908448 */   mtc2      $a0, $18 /* handwritten instruction */
    /* 560C 0000560C 7DFF0010 */  b          .L00005404
    /* 5610 00005610 00988448 */   mtc2      $a0, $19 /* handwritten instruction */
    /* 5614 00005614 7BFF0010 */  b          .L00005404
    /* 5618 00005618 00A08448 */   mtc2      $a0, $20 /* handwritten instruction */
    /* 561C 0000561C 79FF0010 */  b          .L00005404
    /* 5620 00005620 00A88448 */   mtc2      $a0, $21 /* handwritten instruction */
    /* 5624 00005624 77FF0010 */  b          .L00005404
    /* 5628 00005628 00B08448 */   mtc2      $a0, $22 /* handwritten instruction */
    /* 562C 0000562C 0800E003 */  jr         $ra
    /* 5630 00005630 00000000 */   nop
endlabel func_000055B4

glabel func_00005634
    /* 5634 00005634 0800E003 */  jr         $ra
    /* 5638 00005638 00000000 */   nop
endlabel func_00005634

/* Handwritten function */
glabel func_0000563C
    /* 563C 0000563C 71FF0010 */  b          .L00005404
    /* 5640 00005640 00C88448 */   mtc2      $a0, $25 /* handwritten instruction */
    /* 5644 00005644 6FFF0010 */  b          .L00005404
    /* 5648 00005648 00D08448 */   mtc2      $a0, $26 /* handwritten instruction */
    /* 564C 0000564C 6DFF0010 */  b          .L00005404
    /* 5650 00005650 00D88448 */   mtc2      $a0, $27 /* handwritten instruction */
    /* 5654 00005654 6BFF0010 */  b          .L00005404
    /* 5658 00005658 00E08448 */   mtc2      $a0, $28 /* handwritten instruction */
    /* 565C 0000565C 0800E003 */  jr         $ra
    /* 5660 00005660 00000000 */   nop
endlabel func_0000563C

/* Handwritten function */
glabel func_00005664
    /* 5664 00005664 67FF0010 */  b          .L00005404
    /* 5668 00005668 00F08448 */   mtc2      $a0, $30 /* handwritten instruction */
    /* 566C 0000566C 0800E003 */  jr         $ra
    /* 5670 00005670 00000000 */   nop
endlabel func_00005664

/* Handwritten function */
glabel func_00005674
    /* 5674 00005674 00600840 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 5678 00005678 00000000 */  nop
    /* 567C 0000567C 0040093C */  lui        $t1, (0x40000000 >> 16)
    /* 5680 00005680 25400901 */  or         $t0, $t0, $t1
    /* 5684 00005684 00608840 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 5688 00005688 00000000 */  nop
    /* 568C 0000568C C0200400 */  sll        $a0, $a0, 3
    /* 5690 00005690 0000083C */  lui        $t0, %hi(D_000056A4)
    /* 5694 00005694 A4560825 */  addiu      $t0, $t0, %lo(D_000056A4)
    /* 5698 00005698 20400401 */  add        $t0, $t0, $a0 /* handwritten instruction */
    /* 569C 0000569C 08000001 */  jr         $t0
    /* 56A0 000056A0 00000000 */   nop
  alabel D_000056A4
    /* 56A4 000056A4 57FF0010 */  b          .L00005404
    /* 56A8 000056A8 00004248 */   cfc2      $v0, $0 /* handwritten instruction */
    /* 56AC 000056AC 55FF0010 */  b          .L00005404
    /* 56B0 000056B0 00084248 */   cfc2      $v0, $1 /* handwritten instruction */
    /* 56B4 000056B4 53FF0010 */  b          .L00005404
    /* 56B8 000056B8 00104248 */   cfc2      $v0, $2 /* handwritten instruction */
    /* 56BC 000056BC 51FF0010 */  b          .L00005404
    /* 56C0 000056C0 00184248 */   cfc2      $v0, $3 /* handwritten instruction */
    /* 56C4 000056C4 4FFF0010 */  b          .L00005404
    /* 56C8 000056C8 00204248 */   cfc2      $v0, $4 /* handwritten instruction */
    /* 56CC 000056CC 4DFF0010 */  b          .L00005404
    /* 56D0 000056D0 00284248 */   cfc2      $v0, $5 /* handwritten instruction */
    /* 56D4 000056D4 4BFF0010 */  b          .L00005404
    /* 56D8 000056D8 00304248 */   cfc2      $v0, $6 /* handwritten instruction */
    /* 56DC 000056DC 49FF0010 */  b          .L00005404
    /* 56E0 000056E0 00384248 */   cfc2      $v0, $7 /* handwritten instruction */
    /* 56E4 000056E4 47FF0010 */  b          .L00005404
    /* 56E8 000056E8 00404248 */   cfc2      $v0, $8 /* handwritten instruction */
    /* 56EC 000056EC 45FF0010 */  b          .L00005404
    /* 56F0 000056F0 00484248 */   cfc2      $v0, $9 /* handwritten instruction */
    /* 56F4 000056F4 43FF0010 */  b          .L00005404
    /* 56F8 000056F8 00504248 */   cfc2      $v0, $10 /* handwritten instruction */
    /* 56FC 000056FC 41FF0010 */  b          .L00005404
    /* 5700 00005700 00584248 */   cfc2      $v0, $11 /* handwritten instruction */
    /* 5704 00005704 3FFF0010 */  b          .L00005404
    /* 5708 00005708 00604248 */   cfc2      $v0, $12 /* handwritten instruction */
    /* 570C 0000570C 3DFF0010 */  b          .L00005404
    /* 5710 00005710 00684248 */   cfc2      $v0, $13 /* handwritten instruction */
    /* 5714 00005714 3BFF0010 */  b          .L00005404
    /* 5718 00005718 00704248 */   cfc2      $v0, $14 /* handwritten instruction */
    /* 571C 0000571C 39FF0010 */  b          .L00005404
    /* 5720 00005720 00784248 */   cfc2      $v0, $15 /* handwritten instruction */
    /* 5724 00005724 37FF0010 */  b          .L00005404
    /* 5728 00005728 00804248 */   cfc2      $v0, $16 /* handwritten instruction */
    /* 572C 0000572C 35FF0010 */  b          .L00005404
    /* 5730 00005730 00884248 */   cfc2      $v0, $17 /* handwritten instruction */
    /* 5734 00005734 33FF0010 */  b          .L00005404
    /* 5738 00005738 00904248 */   cfc2      $v0, $18 /* handwritten instruction */
    /* 573C 0000573C 31FF0010 */  b          .L00005404
    /* 5740 00005740 00984248 */   cfc2      $v0, $19 /* handwritten instruction */
    /* 5744 00005744 2FFF0010 */  b          .L00005404
    /* 5748 00005748 00A04248 */   cfc2      $v0, $20 /* handwritten instruction */
    /* 574C 0000574C 2DFF0010 */  b          .L00005404
    /* 5750 00005750 00A84248 */   cfc2      $v0, $21 /* handwritten instruction */
    /* 5754 00005754 2BFF0010 */  b          .L00005404
    /* 5758 00005758 00B04248 */   cfc2      $v0, $22 /* handwritten instruction */
    /* 575C 0000575C 29FF0010 */  b          .L00005404
    /* 5760 00005760 00B84248 */   cfc2      $v0, $23 /* handwritten instruction */
    /* 5764 00005764 27FF0010 */  b          .L00005404
    /* 5768 00005768 00C04248 */   cfc2      $v0, $24 /* handwritten instruction */
    /* 576C 0000576C 25FF0010 */  b          .L00005404
    /* 5770 00005770 00C84248 */   cfc2      $v0, $25 /* handwritten instruction */
    /* 5774 00005774 23FF0010 */  b          .L00005404
    /* 5778 00005778 00D04248 */   cfc2      $v0, $26 /* handwritten instruction */
    /* 577C 0000577C 21FF0010 */  b          .L00005404
    /* 5780 00005780 00D84248 */   cfc2      $v0, $27 /* handwritten instruction */
    /* 5784 00005784 1FFF0010 */  b          .L00005404
    /* 5788 00005788 00E04248 */   cfc2      $v0, $28 /* handwritten instruction */
    /* 578C 0000578C 1DFF0010 */  b          .L00005404
    /* 5790 00005790 00E84248 */   cfc2      $v0, $29 /* handwritten instruction */
    /* 5794 00005794 1BFF0010 */  b          .L00005404
    /* 5798 00005798 00F04248 */   cfc2      $v0, $30 /* handwritten instruction */
    /* 579C 0000579C 19FF0010 */  b          .L00005404
    /* 57A0 000057A0 00F84248 */   cfc2      $v0, $31 /* handwritten instruction */
endlabel func_00005674

/* Handwritten function */
glabel func_000057A4
    /* 57A4 000057A4 00600840 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 57A8 000057A8 00000000 */  nop
    /* 57AC 000057AC 0040093C */  lui        $t1, (0x40000000 >> 16)
    /* 57B0 000057B0 25400901 */  or         $t0, $t0, $t1
    /* 57B4 000057B4 00608840 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 57B8 000057B8 00000000 */  nop
    /* 57BC 000057BC C0280500 */  sll        $a1, $a1, 3
    /* 57C0 000057C0 0000083C */  lui        $t0, %hi(D_000057D4)
    /* 57C4 000057C4 D4570825 */  addiu      $t0, $t0, %lo(D_000057D4)
    /* 57C8 000057C8 20400501 */  add        $t0, $t0, $a1 /* handwritten instruction */
    /* 57CC 000057CC 08000001 */  jr         $t0
    /* 57D0 000057D0 00000000 */   nop
  alabel D_000057D4
    /* 57D4 000057D4 0BFF0010 */  b          .L00005404
    /* 57D8 000057D8 0000C448 */   ctc2      $a0, $0 /* handwritten instruction */
    /* 57DC 000057DC 09FF0010 */  b          .L00005404
    /* 57E0 000057E0 0008C448 */   ctc2      $a0, $1 /* handwritten instruction */
    /* 57E4 000057E4 07FF0010 */  b          .L00005404
    /* 57E8 000057E8 0010C448 */   ctc2      $a0, $2 /* handwritten instruction */
    /* 57EC 000057EC 05FF0010 */  b          .L00005404
    /* 57F0 000057F0 0018C448 */   ctc2      $a0, $3 /* handwritten instruction */
    /* 57F4 000057F4 03FF0010 */  b          .L00005404
    /* 57F8 000057F8 0020C448 */   ctc2      $a0, $4 /* handwritten instruction */
    /* 57FC 000057FC 01FF0010 */  b          .L00005404
    /* 5800 00005800 0028C448 */   ctc2      $a0, $5 /* handwritten instruction */
    /* 5804 00005804 FFFE0010 */  b          .L00005404
    /* 5808 00005808 0030C448 */   ctc2      $a0, $6 /* handwritten instruction */
    /* 580C 0000580C FDFE0010 */  b          .L00005404
    /* 5810 00005810 0038C448 */   ctc2      $a0, $7 /* handwritten instruction */
    /* 5814 00005814 FBFE0010 */  b          .L00005404
    /* 5818 00005818 0040C448 */   ctc2      $a0, $8 /* handwritten instruction */
    /* 581C 0000581C F9FE0010 */  b          .L00005404
    /* 5820 00005820 0048C448 */   ctc2      $a0, $9 /* handwritten instruction */
    /* 5824 00005824 F7FE0010 */  b          .L00005404
    /* 5828 00005828 0050C448 */   ctc2      $a0, $10 /* handwritten instruction */
    /* 582C 0000582C F5FE0010 */  b          .L00005404
    /* 5830 00005830 0058C448 */   ctc2      $a0, $11 /* handwritten instruction */
    /* 5834 00005834 F3FE0010 */  b          .L00005404
    /* 5838 00005838 0060C448 */   ctc2      $a0, $12 /* handwritten instruction */
    /* 583C 0000583C F1FE0010 */  b          .L00005404
    /* 5840 00005840 0068C448 */   ctc2      $a0, $13 /* handwritten instruction */
    /* 5844 00005844 EFFE0010 */  b          .L00005404
    /* 5848 00005848 0070C448 */   ctc2      $a0, $14 /* handwritten instruction */
    /* 584C 0000584C EDFE0010 */  b          .L00005404
    /* 5850 00005850 0078C448 */   ctc2      $a0, $15 /* handwritten instruction */
    /* 5854 00005854 EBFE0010 */  b          .L00005404
    /* 5858 00005858 0080C448 */   ctc2      $a0, $16 /* handwritten instruction */
    /* 585C 0000585C E9FE0010 */  b          .L00005404
    /* 5860 00005860 0088C448 */   ctc2      $a0, $17 /* handwritten instruction */
    /* 5864 00005864 E7FE0010 */  b          .L00005404
    /* 5868 00005868 0090C448 */   ctc2      $a0, $18 /* handwritten instruction */
    /* 586C 0000586C E5FE0010 */  b          .L00005404
    /* 5870 00005870 0098C448 */   ctc2      $a0, $19 /* handwritten instruction */
    /* 5874 00005874 E3FE0010 */  b          .L00005404
    /* 5878 00005878 00A0C448 */   ctc2      $a0, $20 /* handwritten instruction */
    /* 587C 0000587C E1FE0010 */  b          .L00005404
    /* 5880 00005880 00A8C448 */   ctc2      $a0, $21 /* handwritten instruction */
    /* 5884 00005884 DFFE0010 */  b          .L00005404
    /* 5888 00005888 00B0C448 */   ctc2      $a0, $22 /* handwritten instruction */
    /* 588C 0000588C DDFE0010 */  b          .L00005404
    /* 5890 00005890 00B8C448 */   ctc2      $a0, $23 /* handwritten instruction */
    /* 5894 00005894 DBFE0010 */  b          .L00005404
    /* 5898 00005898 00C0C448 */   ctc2      $a0, $24 /* handwritten instruction */
    /* 589C 0000589C D9FE0010 */  b          .L00005404
    /* 58A0 000058A0 00C8C448 */   ctc2      $a0, $25 /* handwritten instruction */
    /* 58A4 000058A4 D7FE0010 */  b          .L00005404
    /* 58A8 000058A8 00D0C448 */   ctc2      $a0, $26 /* handwritten instruction */
    /* 58AC 000058AC D5FE0010 */  b          .L00005404
    /* 58B0 000058B0 00D8C448 */   ctc2      $a0, $27 /* handwritten instruction */
    /* 58B4 000058B4 D3FE0010 */  b          .L00005404
    /* 58B8 000058B8 00E0C448 */   ctc2      $a0, $28 /* handwritten instruction */
    /* 58BC 000058BC D1FE0010 */  b          .L00005404
    /* 58C0 000058C0 00E8C448 */   ctc2      $a0, $29 /* handwritten instruction */
    /* 58C4 000058C4 CFFE0010 */  b          .L00005404
    /* 58C8 000058C8 00F0C448 */   ctc2      $a0, $30 /* handwritten instruction */
    /* 58CC 000058CC 0800E003 */  jr         $ra
    /* 58D0 000058D0 00000000 */   nop
endlabel func_000057A4
    /* 58D4 000058D4 00000000 */  nop
    /* 58D8 000058D8 00000000 */  nop
    /* 58DC 000058DC 00000000 */  nop
